version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hrtc-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pnfmiq392yy7"
s3_prefix = "hrtc-sam"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
